### PR TITLE
Hotfix gitbook sync

### PR DESCRIPTION
**Pull request by huyu335**
Verification:
* Add markdown verification to test.yml
* PR title should contain "Module" or "Subworkflow"

Generation of Markdown:
* MR commit message should contain "Module" or "Subworkflow"

Request review along with gitbook tutorial: https://app.gitbook.com/o/Txb2lda7D1fX9CVuQbQ0/s/x32s1acwH78k3hruISMe/~/diff/~/changes/20/contributing

### CODE REVIEW

**Comment by huyu335** [comment]
Subworkflow failed in testing, but I think it's okay?

**Comment by rhshah** [comment]
Maybe we should discuss if the subworkflows that are derived from nf-core should be part of this? Not sure, as far my understanding goes we decided not to have those, if that is correct we should remove such subworkflows.

**Comment by huyu335** [comment]
I think that's our own subworkflow, not from nf-core. Maybe we added the subworkflow before the auto-testing was implemented?

**Comment by rhshah** [comment]
```groovy
include { SAMTOOLS_INDEX               } from '../../../modules/nf-core/samtools/index/main'
```

it is trying to find nf-core module and thus it is failing.

**Pull request closed without merging**
