### PR TITLE
Remove 'name' field as mandatory from environment_schema.json

### LINKED ISSUE #142: Will need to update environment_schema.json to make 'name' field not mandatory
Saw on nf-core slack that a new change was introduced today which throws an error if the user has a 'name' field in their module's environment.yml. the MSK environment_schema.json requires a 'name' field, so this will need to be made optional to account for this change.

### PR DESCRIPTION
**Pull request by rnaidu**
## PR checklist

Closes #142  

- [x] Removing 'name' field in environment_schema.json since updated version of nf-core tools released today is throwing an error if provided in user's environment.yml.
- [x] Removing 'defaults' channel field in environment_schema.json since updated version of nf-core tools released today is throwing an error if provided in user's environment.yml.
- [x] Inserting glob pattern under 'dependencies' field to match what is required by nf-core lint check

### CODE REVIEW

**Review by buehlere — CHANGES_REQUESTED** [review]
I'm thinking about this in two ways.

Either we just merge in the schema change and let people fix their individual modules when they see the lint failing. Or we could just go ahead and remove the `name` field all modules. 

I think both should be pretty easy. I'm leaning towards just removing it for all modules. 

I also noticed `defaults` is being removed is that part of the linting update?

**Comment by rnaidu** [comment]
> I'm thinking about this in two ways.
> 
> Either we just merge in the schema change and let people fix their individual modules when they see the lint failing. Or we could just go ahead and remove the `name` field all modules.
> 
> I think both should be pretty easy. I'm leaning towards just removing it for all modules.
> 
> I also noticed `defaults` is being removed is that part of the linting update?

@buehlere I agree on removing 'name' for all modules, since the conversation on the nf-core slack said the 'name' field will be removed from the new module template moving forward. I'll add that change now 


I think removing 'defaults' is part of the linting update as well since I updated my nf-core and used this command to create a module off the updated nf-core modules template. The new module created by the updated template has both 'name' and 'defaults' removed. I reached out to the nf-core maintainer in that slack thread in case we want a confirmation from them before merging the schema.

`nf-core modules create testing --author @rnaidu --label process_low --meta`

**Comment by rnaidu** [comment]
Final environment_schema.json includes:

- removal of 'name' field
- removal of 'defaults' field under channels.
- addition of glob pattern set by nf-core lint under 'dependencies'

**Review by buehlere — APPROVED** [review]
looks good to me!

**Pull request merged**
